### ISSUE TITLE
Documentation and 2 questions

### ISSUE THREAD

**Issue by hetzbh** [jarrpa/storage-ha#12]
Hello,

GlusterFS 3.12 and up is using storhaug instead of gluster nfs.ganesha commands, but sadly, there isn't any documentation how to actually use it. Would you mind adding a simple document how to use it please? I'll give an example scenario:
* 2 nodes, on each one there are 2 drives, 1st for the OS and the 2nd for glusterfs. 2 NICS on each node - 1 for internal communication for nodes, other NIC for serving content from nfs-ganesha.
* Gluster will be created for a simple replication (HA) for 2 nodes
* NFS Ganesha will be installed, and will be used along with pcs and a cluterIP.

Where in this scenario does storhaug goes in and what should I type? that sort of document would help us a lot (you can see the frustration of a missing documentation on the gluster-user mailing list).

Another question: looking at the scripts, you're trying to parse ganesha.conf. Why? it should only include an "include" line for the "exports" directory in /etc/ganesha/exports/

Final question: with storhaug, do I need to create ganesha-ha.conf file or does storhaug creates it? 

Thanks

**Comment by AmritasyaPutra** [comment]
Is there documentation in planning?

**Comment by kalebskeithley** [comment]
storhaug is now at https://github.com/gluster/storhaug/

and documentation is at https://github.com/gluster/storhaug/wiki

**Comment by AmritasyaPutra** [comment]
Thank you for the update!
